# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    outputs:
      runs-on: ${{ steps.runs-on.outputs.label }} 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sleep 300
          env | sort

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo fdisk -l
          echo "---------------"
          sudo lsblk
          echo "---------------"
          sudo cat /etc/fstab
          
      - name: Set the value
        id: runs-on
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
          echo "label=$(curl -fsSL https://this-is-nats.appscode.ninja/runs-on/${{ github.repository_owner }}?visibility=${{ github.repository_visibility }})" >> $GITHUB_OUTPUT

  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use the value
        id: step_two
        run: |
          echo "${{ needs.build.outputs.runs-on }}" # This will output 'yellow'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: env | sort

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo fdisk -l
          echo "---------------"
          sudo lsblk
          echo "---------------"
          sudo cat /etc/fstab

